- .flake8
- .github/workflows/test.yml
- decode/__init__.py
- decode/core/__init__.py
- decode/core/array/classes.py
- decode/core/array/decorators.py
- decode/core/array/functions.py
- decode/core/cube/classes.py
- decode/core/cube/functions.py
- decode/io/__init__.py
- decode/io/functions.py
- decode/logging/__init__.py
- decode/models/__init__.py
- decode/models/functions.py
- decode/plot/__init__.py
- decode/plot/functions.py
- decode/utils/__init__.py
- decode/utils/misc/functions.py
- decode/utils/ndarray/functions.py
- docs/conf.py
- tests/test_metadata.py
> Format codes

- decode/__init__.py
- docs/conf.py
- pyproject.toml
- tests/test_metadata.py
> Release v0.5.7

- decode/__init__.py
- docs/conf.py
- poetry.lock
- pyproject.toml
- tests/test_metadata.py
> Release v0.5.8

- decode/__init__.py
- pyproject.toml
- tests/test_metadata.py
> Release v0.6.0

- decode/utils.py
- poetry.lock
- pyproject.toml
> Use morecopy for copying function

- .devcontainer/devcontainer.json
- LICENSE
- README.md
- decode/__init__.py
- docs/conf.py
- poetry.lock
- pyproject.toml
- tests/test_metadata.py
> Release v0.7.0

- decode/__init__.py
- poetry.lock
- pyproject.toml
- tests/test_metadata.py
> Fix minimum requirement of matplotlib

- CITATION.cff
- LICENSE
- README.md
- decode/__init__.py
- docs/conf.py
- pyproject.toml
> Release v2.0.0

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2.1.0

- decode/select.py
- tests/test_select.py
> Fix function for selecting DEMS

- CITATION.cff
- README.md
- decode/__init__.py
- decode/plot.py
- pyproject.toml
> Release v2.2.0

- CITATION.cff
- README.md
- decode/__init__.py
- decode/plot.py
- pyproject.toml
> Release v2.3.0

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2.4.0

- CITATION.cff
- README.md
- decode/__init__.py
- decode/convert.py
- pyproject.toml
- tests/test_convert.py
> Do not update frame coordinate

- CITATION.cff
- README.md
- decode/__init__.py
- decode/make.py
- pyproject.toml
> Fix dtype of d2_mkid_type in Cube

- CITATION.cff
- README.md
- decode/__init__.py
- decode/make.py
- pyproject.toml
> Update make module

- .devcontainer/devcontainer.json
- decode/convert.py
- decode/make.py
- decode/plot.py
- poetry.lock
- pyproject.toml
- tests/test_convert.py
> Use cube class of DEMS in making cube

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2.6.0

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Fix qlook module

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Update weighting method of quick look

- decode/qlook.py
> Add qlook command for still (and any type of) observations

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2.8.0

- decode/qlook.py
> Keep attributes in qlook functions

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2.12.0

- decode/qlook.py
#153 Correct for atmospheric transmission in qlook
> Correct for atmospheric transmission qlook

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2.13.0

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Fix missing conditional branches for X/Y scan

- decode/assign.py
- decode/qlook.py
> Add qlook command for daisy scan

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Update qlook options for loading DEMS

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Fix qlook options for min/max frequencies

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Add qlook option for debugging

- decode/qlook.py
#178 add  atm-correction for raster
> add  atm-correction for raster

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Fix labeling method of qlook daisy command 

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2024.8.0

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Release v2024.8.1

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2024.8.2

- CITATION.cff
- README.md
- decode/__init__.py
- decode/qlook.py
- pyproject.toml
> Fix aspect ratio of qlook map images

- CITATION.cff
- README.md
- decode/__init__.py
- decode/utils.py
- pyproject.toml
- tests/test_utils.py
> Add utility to get phase label of 1D DataArray

- decode/qlook.py
#150  Add signal spike removal code in qlook
> Add signal spike removal

- decode/qlook.py
> Update definition of major/minor axes of 2D Gaussian fitting

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2024.9.1

- decode/qlook.py
I fixed the direction of the horizontal axis in #214.
> Fix reversed sky longitude axis in daisy/raster qlook

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2024.9.2

- CITATION.cff
- README.md
- decode/__init__.py
- pyproject.toml
> Release v2024.11.0

- CITATION.cff
> Fix release date

- CITATION.cff
- README.md
- decode/__init__.py
- decode/fit.py
- pyproject.toml
- tests/test_assign.py
> Remove deprecated data type (numpy.float_)

- CITATION.cff
- README.md
- decode/__init__.py
- decode/convert.py
- pyproject.toml
> Fix return data type of DataArray in convert.units
